language: php

php:
    - "5.4"
    - "5.5"
    - "5.6"
    - "7.0"

before_install:
    - echo "memory_limit=3G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - composer self-update --no-interaction

install:
    - composer install --prefer-dist --no-interaction --no-scripts

script: false
